import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
import { mainTheme } from './styles/theme';
import { BrowserRouter } from 'react-router-dom';
import ReactDOM from 'react-dom/client';
import { ThemeProvider } from 'styled-components';
import App from './App';
import { UserProvider } from './contexts/UserContext';
import { CartProvider } from './contexts/CartContext';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(ThemeProvider, { theme: mainTheme, children: _jsx(UserProvider, { children: _jsx(CartProvider, { children: _jsx(App, {}) }) }) }) }) }));
